import type { Combatant, ResourceGeneration, ResourceRegen } from '../../engine';
import { seconds } from '../../engine';

/**
 * How much damage is worth one point of rage, at level 60.
 *
 * The full formulas are:
 *
 *     rage from dealing damage = damage / 230.6 * 7.5
 *     rage from taking damage  = damage / 230.6 * 2.5
 *
 * The factor scales with level in the real game, which is why it is named
 * rather than folded into the coefficients below.
 */
export const RAGE_CONVERSION_FACTOR = 230.6;

/** Rage per point of damage dealt. */
export const RAGE_PER_DAMAGE_DEALT = 7.5 / RAGE_CONVERSION_FACTOR;

/** Rage per point of damage taken. Taking a hit is worth a third of landing one. */
export const RAGE_PER_DAMAGE_TAKEN = 2.5 / RAGE_CONVERSION_FACTOR;

/**
 * Rage generated by landing an auto-attack.
 *
 * Proportional to damage, with no flat component, so a missed or dodged swing
 * generates nothing at all. That is what makes a high-miss build rage-starved
 * as well as low-damage, and it is why the dual-wield miss penalty hurts twice.
 */
export const RAGE_FROM_AUTO_ATTACK: ResourceGeneration = {
  resource: 'rage',
  perDamage: RAGE_PER_DAMAGE_DEALT,
};

/** Rage generated by being hit. */
export const RAGE_FROM_DAMAGE_TAKEN: ResourceGeneration = {
  resource: 'rage',
  perDamage: RAGE_PER_DAMAGE_TAKEN,
};

/* --- Energy --- */

/** Energy arrives in fixed batches rather than scaling with anything. */
export const ENERGY_PER_TICK = 20;
export const ENERGY_TICK_INTERVAL_MS = seconds(2);

export const ENERGY_REGEN: ResourceRegen = {
  resource: 'energy',
  intervalMs: ENERGY_TICK_INTERVAL_MS,
  amountPerTick: () => ENERGY_PER_TICK,
};

/* --- Mana --- */

/** Mana ticks on the same two-second cadence as energy. */
export const MANA_TICK_INTERVAL_MS = seconds(2);

/**
 * Fraction of the five-second mana figure that arrives on each two-second tick.
 *
 * 0.4 is exactly 2/5, so MP5 prorated to the tick interval. The two numbers
 * agree by construction rather than by coincidence, and a character regenerates
 * exactly its stated MP5 over any five seconds of uninterrupted ticking.
 */
export const MANA_TICK_FRACTION = MANA_TICK_INTERVAL_MS / seconds(5);

/**
 * How long spending mana suppresses regeneration.
 *
 * The "five second rule": after spending mana, regeneration stops until five
 * seconds have passed without spending again.
 */
export const MANA_REGEN_LOCKOUT_MS = seconds(5);

/**
 * Mana regeneration, including the five second rule.
 *
 * While inside the lockout, a character regenerates only the fraction its
 * `manaRegenBypass` stat allows — the stat that reads "allows X% of your mana
 * regeneration to continue while casting". With no such stat, the answer is
 * zero and the tick does nothing.
 *
 * The tick still fires during the lockout rather than being cancelled, so
 * regeneration resumes by itself the moment five quiet seconds pass.
 */
export const MANA_REGEN: ResourceRegen = {
  resource: 'mana',
  intervalMs: MANA_TICK_INTERVAL_MS,
  amountPerTick: (actor, context) => manaPerTick(actor, context.clock.now()),
};

/** Mana granted by one tick, given when mana was last spent. */
export function manaPerTick(actor: Combatant, now: number): number {
  const full = actor.stats.get('manaPer5') * MANA_TICK_FRACTION;
  if (full <= 0) return 0;

  const casting = actor.spentWithin('mana', now, MANA_REGEN_LOCKOUT_MS);
  if (!casting) return full;

  const bypass = clampPercent(actor.stats.get('manaRegenBypass')) / 100;
  return full * bypass;
}

function clampPercent(value: number): number {
  if (!Number.isFinite(value) || value <= 0) return 0;
  return Math.min(100, value);
}

/**
 * The regeneration timers a character has, by the resources it owns.
 *
 * Rage is absent on purpose: it does not regenerate on a timer, it is earned by
 * fighting.
 */
export function regenerationFor(resources: readonly string[]): ResourceRegen[] {
  const regen: ResourceRegen[] = [];
  if (resources.includes('energy')) regen.push(ENERGY_REGEN);
  if (resources.includes('mana')) regen.push(MANA_REGEN);
  return regen;
}
