import type { Talent, WarriorTreeId } from './Talent';

/**
 * The Warrior talent trees.
 *
 * Source: the World of Warcraft: Forever talent calculator,
 * https://www.wowhead.com/forever/talent-calc/warrior
 *
 * Read from that calculator's own grid rather than typed from a screenshot:
 * every row, column, rank maximum, tier requirement and prerequisite below came
 * out of the markup it renders, so the layout here is the layout it draws.
 *
 * NOTHING HERE HAS ANY EFFECT ON A SIMULATION. These are names, positions and
 * text. Spending a point changes what the interface shows and nothing else --
 * no damage number, no cooldown, no resource. Talents are the one thing on the
 * "data the project still needs" list that is now half-answered: the tree is
 * real, the effects are not implemented.
 *
 * TWO THINGS THIS SOURCE SETTLES, AND ONE IT BREAKS:
 *
 * 1. Mortal Strike, Bloodthirst and Shield Slam are 31-point capstones in three
 *    different trees. With 51 points a warrior can reach exactly one. The
 *    ability spreadsheet lists all three with no note of exclusivity, and
 *    `abilitiesForClass` currently hands out all three at once.
 * 2. Spearing Strike is an Arms talent, which is why it had no Classic
 *    counterpart to check against.
 * 3. CONFLICT: this calculator gives Mortal Strike "weapon damage plus 85".
 *    WoWForeverWarriorAbilities.xlsx gives it a base of 160. Both are Forever
 *    sources and they disagree. The abilities file still uses 160, because that
 *    is the sheet the ruleset owner supplied directly; this is flagged in
 *    docs/warrior-abilities.md and needs resolving.
 */

interface TalentRow {
  readonly row: number;
  readonly col: number;
  readonly ranks: number;
  readonly name: string;
  readonly icon: string;
  readonly tier: number;
  readonly requires?: string;
  readonly requiresRanks?: number;
  readonly description: string;
}

/** Turn a display name into the id used everywhere else. */
export function talentId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
}

const ARMS: readonly TalentRow[] = [
  { row: 0, col: 0, ranks: 3, name: 'Improved Heroic Strike', icon: 'ability_rogue_ambush', tier: 0,
    description: 'Reduces the cost of your Heroic Strike ability by 1 Rage.' },
  { row: 0, col: 1, ranks: 5, name: 'Deflection', icon: 'ability_parry', tier: 0,
    description: 'Increases your Parry chance by 1%.' },
  { row: 0, col: 2, ranks: 3, name: 'Improved Rend', icon: 'ability_gouge', tier: 0,
    description: "Increases the Bleed damage done by your Rend ability by 12%." },
  { row: 1, col: 0, ranks: 2, name: 'Improved Charge', icon: 'ability_warrior_charge', tier: 5,
    description: 'Increases the Rage generated by your Charge ability by 3.' },
  { row: 1, col: 1, ranks: 5, name: 'Improved Tactical Mastery', icon: 'spell_nature_enchantarmor', tier: 5,
    description: 'Tactical Mastery lets you retain up to an additional 3 Rage when you change stances.' },
  { row: 1, col: 3, ranks: 2, name: 'Improved Overpower', icon: 'inv_sword_05', tier: 5,
    description: 'Increases the critical strike chance of your Overpower ability by 25%.' },
  { row: 2, col: 1, ranks: 1, name: 'Anger Management', icon: 'spell_holy_blessingofstamina', tier: 10,
    requires: 'improved_tactical_mastery', requiresRanks: 5,
    description: 'Generates 1 Rage every 3 sec while in combat, and reduces Rage loss while out of combat by 30%.' },
  { row: 2, col: 2, ranks: 3, name: 'Deep Wounds', icon: 'ability_backstab', tier: 10,
    requires: 'improved_rend', requiresRanks: 3,
    description: "Your critical strikes cause your opponent to Bleed, dealing 20% of your melee weapon's average damage over 12 sec." },
  { row: 3, col: 0, ranks: 1, name: 'Spearing Strike', icon: 'inv_spear_01', tier: 15,
    description: 'A brutal attack that deals 40% weapon damage. Deals an additional 80% weapon damage against Giants, Dragonkin, and mounted targets. Mounted targets are dismounted.' },
  { row: 3, col: 1, ranks: 3, name: 'Two-Handed Weapon Specialization', icon: 'inv_axe_09', tier: 15,
    description: 'Increases the damage you deal with two-handed melee weapons by 1%.' },
  { row: 3, col: 2, ranks: 2, name: 'Impale', icon: 'ability_searingarrow', tier: 15,
    description: 'Increases the critical strike damage bonus of your abilities by 10%.' },
  { row: 4, col: 0, ranks: 5, name: 'Bloodthrill', icon: 'inv_sword_01', tier: 20,
    description: 'Your melee attacks against targets afflicted by your Rend have a 2% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 sec.' },
  { row: 4, col: 1, ranks: 1, name: 'Sweeping Strikes', icon: 'ability_rogue_slicedice', tier: 20,
    description: 'Your next 5 melee attacks strike an additional nearby opponent.' },
  { row: 4, col: 2, ranks: 5, name: 'Weaponmaster', icon: 'garrison_weaponupgrade', tier: 20,
    description: "Gives your melee weapon attacks a benefit depending on the weapon. Axe/Polearm: Increases your critical strike chance by 1%. Mace/Staff: Your attacks ignore 3% of your target's armor. Sword: Your successful melee attacks have a 1% chance to trigger an extra attack on the target." },
  { row: 5, col: 0, ranks: 2, name: 'Improved Slam', icon: 'ability_warrior_decisivestrike', tier: 25,
    description: 'Reduces the global cooldown and cast time of your Slam ability by 0.25 sec. In addition, Slam no longer interrupts your melee swing time.' },
  { row: 5, col: 2, ranks: 3, name: 'Improved Hamstring', icon: 'ability_shockwave', tier: 25,
    description: 'Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.' },
  { row: 6, col: 1, ranks: 1, name: 'Mortal Strike', icon: 'ability_warrior_savageblow', tier: 30,
    requires: 'sweeping_strikes', requiresRanks: 1,
    description: 'A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.' },
];

const FURY: readonly TalentRow[] = [
  { row: 0, col: 1, ranks: 5, name: 'Booming Voice', icon: 'spell_nature_purge', tier: 0,
    description: 'Increases the radius of your Battle Shout and Demoralizing Shout abilities by 10%.' },
  { row: 0, col: 2, ranks: 5, name: 'Cruelty', icon: 'ability_rogue_eviscerate', tier: 0,
    description: 'Increases your chance to get a critical strike with melee attacks by 1%.' },
  { row: 1, col: 1, ranks: 5, name: 'Iron Will', icon: 'spell_magic_magearmor', tier: 5,
    description: 'Reduces the duration of Stun and Fear effects inflicted on you by 3%.' },
  { row: 1, col: 2, ranks: 5, name: 'Unbridled Wrath', icon: 'spell_nature_stoneclawtotem', tier: 5,
    description: 'Gives you a 12% chance to generate 1 additional Rage when you deal melee damage with a weapon. This effect is increased to 2 Rage for two-handed weapons.' },
  { row: 2, col: 0, ranks: 3, name: 'Improved Cleave', icon: 'ability_warrior_cleave', tier: 10,
    description: 'Reduces the Rage cost of your Cleave ability by 1.' },
  { row: 2, col: 1, ranks: 1, name: 'Piercing Howl', icon: 'spell_shadow_deathscream', tier: 10,
    description: 'Causes all nearby enemies to be Dazed, reducing movement speed by 50% for 6 sec.' },
  { row: 2, col: 2, ranks: 3, name: 'Blood Craze', icon: 'spell_shadow_summonimp', tier: 10,
    description: 'Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike, dealing damage with Bloodthirst, or suffering more than 20% of your maximum Health from a single attack.' },
  { row: 2, col: 3, ranks: 3, name: 'Boundless Rage', icon: 'ability_warrior_intensifyrage', tier: 10,
    description: 'Increases your maximum Rage by 10.' },
  { row: 3, col: 0, ranks: 5, name: 'Dual Wield Specialization', icon: 'ability_dualwield', tier: 15,
    description: 'Increases your off-hand weapon damage by 5%, off-hand Rage generation by 20%, and chance to hit with off-hand attacks by 2%.' },
  { row: 3, col: 1, ranks: 1, name: 'Raging Blows', icon: 'ability_whirlwind', tier: 15,
    description: 'Causes your Whirlwind to also strike with your off-hand weapon, and reduces the Rage cost of your Cleave ability by 2.' },
  { row: 3, col: 2, ranks: 5, name: 'Enrage', icon: 'spell_shadow_unholyfrenzy', tier: 15,
    description: 'Gives you a 30% chance to deal 2% increased Physical damage for 12 sec after being the victim of any damaging attack.' },
  { row: 3, col: 3, ranks: 2, name: 'Improved Execute', icon: 'inv_sword_48', tier: 15,
    description: 'Reduces the Rage cost of your Execute ability by 3.' },
  { row: 4, col: 0, ranks: 3, name: 'Precision', icon: 'ability_marksmanship', tier: 20,
    description: 'Increases your chance to hit with all abilities and attacks by 1%.' },
  { row: 4, col: 1, ranks: 1, name: 'Death Wish', icon: 'spell_shadow_deathpact', tier: 20,
    description: 'When activated, increases your Physical damage done by 20% and makes you immune to Fear effects, but increases all damage you take by 5%. Lasts 30 sec.' },
  { row: 4, col: 3, ranks: 2, name: 'Improved Intercept', icon: 'ability_rogue_sprint', tier: 20,
    description: 'Reduces the cooldown of your Intercept ability by 5 sec.' },
  { row: 5, col: 0, ranks: 2, name: 'Improved Berserker Rage', icon: 'spell_nature_ancestralguardian', tier: 25,
    description: 'Your Berserker Rage ability will instantly generate 5 Rage and has a 50% chance to remove all movement impairing effects when activated.' },
  { row: 5, col: 2, ranks: 5, name: 'Flurry', icon: 'ability_ghoulfrenzy', tier: 25,
    requires: 'enrage', requiresRanks: 5,
    description: 'Increases your melee attack speed by 5% for your next 3 swings after dealing a melee critical strike.' },
  { row: 6, col: 1, ranks: 1, name: 'Bloodthirst', icon: 'spell_nature_bloodlust', tier: 30,
    requires: 'death_wish', requiresRanks: 1,
    description: 'Instantly attack the target causing damage equal to 35% of your Attack Power plus 30 and increasing your movement speed by 10% for 10 sec.' },
];

const PROTECTION: readonly TalentRow[] = [
  { row: 0, col: 1, ranks: 5, name: 'Shield Specialization', icon: 'inv_shield_06', tier: 0,
    description: 'Increases your chance to Block attacks with your shield by 1% and grants you a 20% chance to generate 5 Rage when you Block.' },
  { row: 0, col: 2, ranks: 5, name: 'Anticipation', icon: 'spell_nature_mirrorimage', tier: 0,
    description: 'Increases your Defense Skill by 4.' },
  { row: 1, col: 0, ranks: 2, name: 'Improved Bloodrage', icon: 'ability_racial_bloodrage', tier: 5,
    description: 'Increases all the Rage generated by your Bloodrage ability by 25%.' },
  { row: 1, col: 2, ranks: 5, name: 'Toughness', icon: 'spell_holy_devotion', tier: 5,
    description: 'Increases your Armor value from items by 2%.' },
  { row: 1, col: 3, ranks: 3, name: 'Improved Thunder Clap', icon: 'ability_thunderclap', tier: 5,
    description: 'Reduces the Rage cost of your Thunder Clap ability by 2.' },
  { row: 2, col: 0, ranks: 1, name: 'Last Stand', icon: 'spell_holy_ashestoashes', tier: 10,
    requires: 'improved_bloodrage', requiresRanks: 2,
    description: 'When activated, this ability temporarily grants you 30% of your maximum health for 20 sec. After the effect expires, the health is lost.' },
  { row: 2, col: 1, ranks: 2, name: 'Master of Defense', icon: 'ability_warrior_shieldguard', tier: 10,
    requires: 'shield_specialization', requiresRanks: 5,
    description: 'Grants you a 50% chance to generate 5 Rage when you Dodge or Parry while a shield is equipped.' },
  { row: 2, col: 2, ranks: 3, name: 'Improved Revenge', icon: 'ability_warrior_revenge', tier: 10,
    description: 'Increases damage dealt by your Revenge ability by 20%.' },
  { row: 2, col: 3, ranks: 3, name: 'Defiance', icon: 'ability_warrior_innerrage', tier: 10,
    description: 'Increases all threat generated in Defensive stance by an additional 5% while a shield is equipped.' },
  { row: 3, col: 0, ranks: 3, name: 'Improved Sunder Armor', icon: 'ability_warrior_sunder', tier: 15,
    description: 'Reduces the Rage cost of your Sunder Armor ability by 1.' },
  { row: 3, col: 1, ranks: 3, name: 'Improved Disarm', icon: 'ability_warrior_disarm', tier: 15,
    description: 'Reduces the cooldown of your Disarm ability by 7 secs.' },
  { row: 3, col: 2, ranks: 1, name: 'Vanguard', icon: 'ability_warrior_shieldcharge', tier: 15,
    description: 'Your Charge ability is now usable while in Defensive Stance.' },
  { row: 4, col: 0, ranks: 2, name: 'Improved Shield Wall', icon: 'ability_warrior_shieldwall', tier: 20,
    description: 'Reduces the cooldown of your Shield Wall ability by 5.5 min.' },
  { row: 4, col: 1, ranks: 1, name: 'Concussion Blow', icon: 'ability_thunderbolt', tier: 20,
    description: 'Stuns the target for 5 sec.' },
  { row: 4, col: 2, ranks: 2, name: 'Improved Shield Bash', icon: 'ability_warrior_shieldbash', tier: 20,
    description: 'Gives your Shield Bash ability a 50% chance to Silence the target for 3 sec.' },
  { row: 4, col: 3, ranks: 5, name: 'Vitality', icon: 'inv_helmet_21', tier: 20,
    description: 'Increases your Stamina and Strength by 2%.' },
  { row: 5, col: 0, ranks: 3, name: 'Focused Rage', icon: 'ability_warrior_focusedrage', tier: 25,
    description: 'Reduces the Rage cost of your offensive abilities by 1.' },
  { row: 5, col: 2, ranks: 5, name: 'Bastion', icon: 'inv_shield_04', tier: 25,
    description: 'Increases all damage you deal by 2% while a shield is equipped.' },
  { row: 6, col: 1, ranks: 1, name: 'Shield Slam', icon: 'inv_shield_05', tier: 30,
    requires: 'concussion_blow', requiresRanks: 1,
    description: 'Slam the target with your shield, causing 421 to 439 damage, increased by your Block Value, and has a 50% chance of dispelling 1 magic effect on the target. Causes a very high amount of threat.' },
];

function build(tree: WarriorTreeId, rows: readonly TalentRow[]): readonly Talent[] {
  return rows.map((row) => ({ ...row, tree, id: talentId(row.name) }));
}

export interface TalentTree {
  readonly id: WarriorTreeId;
  readonly name: string;
  /** Background art, matching the source calculator's own backdrop. */
  readonly accent: string;
  readonly talents: readonly Talent[];
}

export const WARRIOR_TREES: readonly TalentTree[] = [
  { id: 'arms', name: 'Arms', accent: '#b4622a', talents: build('arms', ARMS) },
  { id: 'fury', name: 'Fury', accent: '#a33b2a', talents: build('fury', FURY) },
  { id: 'protection', name: 'Protection', accent: '#3a6f93', talents: build('protection', PROTECTION) },
];

/** Every talent across all three trees, by id. */
export const WARRIOR_TALENTS_BY_ID: ReadonlyMap<string, Talent> = new Map(
  WARRIOR_TREES.flatMap((tree) => tree.talents.map((talent) => [talent.id, talent] as const)),
);
