import { describe, expect, it } from 'vitest';
import {
  abilitiesForBuild,
  abilitiesForClass,
} from '../../src/game/abilities/abilitiesForClass';
import { talentBuild } from '../../src/game/talents/talentBuild';
import {
  BLOODRAGE_INSTANT_RAGE,
  BLOODRAGE_RAGE_OVER_TIME,
} from '../../src/game/auras/warrior';
import { WARRIOR_TALENT_EFFECTS } from '../../src/game/talents/warriorEffects';
import { createDefaultProfile } from '../../src/profiles';
import { runProfileBatch } from '../../src/simulator';
import { startingEquipmentFor } from '../../src/game/items/startingSets';
import { legalise } from '../helpers/legalTalents';

/*
 * Bloodrage and its talent, Focused Rage, and the Uses column that makes an
 * ability dealing no damage visible at all.
 *
 * Every figure written out by hand from the ruleset owner's words and the
 * captured tooltips.
 */

function berserker(talents: Record<string, number> = {}, iterations = 300) {
  const base = createDefaultProfile();
  return runProfileBatch({
    ...base,
    character: { ...base.character, combatStyle: 'dual_wield', stance: 'berserker' },
    equipment: startingEquipmentFor('warrior', 'dual_wield'),
    talents,
    simulation: { ...base.simulation, iterations, seed: 5, durationSeconds: 60 },
  } as never);
}

// ---------------------------------------------------------------------------
// Bloodrage
// ---------------------------------------------------------------------------

describe('Bloodrage', () => {
  it('is ten on cast and ten more over ten seconds', () => {
    expect(BLOODRAGE_INSTANT_RAGE).toBe(10);
    expect(BLOODRAGE_RAGE_OVER_TIME).toBe(10);
  });

  it('is cast, generates, and is attributed -- all three', () => {
    /*
     * Reported as possibly broken in one of three ways. It is none of them on
     * a build whose list contains it: one cast in a sixty second fight, on a
     * sixty second cooldown, for twenty rage across eleven events.
     */
    const rage = berserker().rage.gained.find((row) => row.sourceId === 'bloodrage');
    expect(rage).toBeDefined();
    // Twenty per cast; a little over one cast fits in a sixty second fight
    // because fight length varies.
    expect(rage!.amount).toBeGreaterThan(20);
    // One instant grant plus ten ticks, per cast.
    expect(rage!.count).toBeGreaterThan(10);
  });

  it('appears in the breakdown even though it deals no damage', () => {
    const row = berserker().abilities.find((entry) => entry.abilityName === 'Bloodrage');
    expect(row).toBeDefined();
    expect(row!.damage).toBe(0);
    expect(row!.uses).toBeGreaterThan(0);
  });
});

describe('Improved Bloodrage', () => {
  it('raises ALL the rage by half at 2/2', () => {
    /*
     * "Increases all the Rage generated by your Bloodrage ability by 25/50%",
     * so at 2/2 the ten on cast becomes fifteen AND the ten over ten seconds
     * becomes fifteen -- both halves, which is what "all" means.
     */
    const plain = berserker().rage.gained.find((r) => r.sourceId === 'bloodrage')!;
    const talented = berserker(legalise({ improved_bloodrage: 2 })).rage.gained.find(
      (r) => r.sourceId === 'bloodrage',
    )!;

    expect(talented.amount / plain.amount).toBeCloseTo(1.5, 1);
    // The same number of EVENTS: the ticks are bigger, not more frequent.
    expect(talented.count).toBeCloseTo(plain.count, 0);
  });

  it('raises it by a quarter at 1/2', () => {
    const plain = berserker().rage.gained.find((r) => r.sourceId === 'bloodrage')!;
    const one = berserker(legalise({ improved_bloodrage: 1 })).rage.gained.find(
      (r) => r.sourceId === 'bloodrage',
    )!;
    expect(one.amount / plain.amount).toBeCloseTo(1.25, 1);
  });

  it('is no longer reported as unmodelled', () => {
    /*
     * Its reason said "Bloodrage is castable but inert", which was true when
     * written and stopped being true the day Bloodrage got its periodic. A
     * reason is a claim about the engine on the day it was made.
     */
    expect(WARRIOR_TALENT_EFFECTS.improved_bloodrage.map((e) => e.kind)).toEqual([
      'abilityBonus',
    ]);
  });
});

// ---------------------------------------------------------------------------
// Focused Rage
// ---------------------------------------------------------------------------

describe('Focused Rage', () => {
  /*
   * Built from the TALENT BUILD rather than from an allocation, because
   * `abilitiesForClass` enforces legality and Focused Rage alone is not a
   * legal allocation -- it would be stripped. Padding it with `legalise`
   * instead drags in Improved Thunder Clap, which moves one of the very
   * numbers under test.
   *
   * This isolates the one talent.
   */
  const costs = (talents: Record<string, number>) => {
    const abilities = abilitiesForBuild(
      'warrior',
      'one_hand_shield',
      talentBuild('warrior', talents, { hasShield: true }),
    );
    return (name: string) => abilities.find((a) => a.name === name)?.cost?.amount;
  };

  it('takes three rage off anything that rolls a combat table', () => {
    /*
     * The ruleset owner's definition of "your offensive abilities": an
     * ability is offensive if it is PROCESSED THROUGH A COMBAT TABLE.
     *
     * Focused Rage alone here, not padded with `legalise`, so nothing else
     * can be moving these numbers.
     */
    const plain = costs({});
    const talented = costs({ focused_rage: 3 });

    for (const name of ['Heroic Strike', 'Thunder Clap', 'Sunder Armor', 'Revenge']) {
      expect(talented(name), name).toBe(plain(name)! - 3);
    }
  });

  it('takes NOTHING off an ability with no combat table', () => {
    // Battle Shout is the ruleset owner's own counter-example.
    const plain = costs({});
    const talented = costs({ focused_rage: 3 });
    expect(talented('Battle Shout')).toBe(plain('Battle Shout'));
    expect(talented('Bloodrage')).toBe(plain('Bloodrage'));
  });

  it('scales one rage a rank', () => {
    for (const rank of [1, 2, 3]) {
      expect(costs({ focused_rage: rank })('Sunder Armor')).toBe(15 - rank);
    }
  });

  it('stacks with a per-ability reduction rather than replacing it', () => {
    // Improved Heroic Strike takes a rage a rank off Heroic Strike alone.
    // Both talents apply, and a warrior with both pays for neither twice.
    const both = costs({ focused_rage: 3, improved_heroic_strike: 3 });
    expect(both('Heroic Strike')).toBe(15 - 3 - 3);
  });

  it('cannot take a cost below zero', () => {
    const cheap = costs({ focused_rage: 3 })('Revenge');
    expect(cheap).toBeGreaterThanOrEqual(0);
  });

  it('is still gated by the tier, like every other talent', () => {
    /*
     * Three points in Focused Rage alone is not a legal allocation, so
     * `abilitiesForClass` strips it -- which is why the tests above build the
     * effects directly. A build that cannot be had must not be measurable.
     */
    const illegal = abilitiesForClass('warrior', 'one_hand_shield', { focused_rage: 3 });
    expect(illegal.find((a) => a.name === 'Sunder Armor')?.cost?.amount).toBe(15);

    const legal = abilitiesForClass('warrior', 'one_hand_shield', legalise({ focused_rage: 3 }));
    expect(legal.find((a) => a.name === 'Sunder Armor')?.cost?.amount).toBe(12);
  });

  it('is derived from the attack table, not from a list of ids', () => {
    /*
     * A list would need editing every time an ability was added, and the edit
     * that was forgotten would make the talent silently weaker.
     */
    expect(WARRIOR_TALENT_EFFECTS.focused_rage).toEqual([{ kind: 'attackAbilityCost' }]);
  });
});

// ---------------------------------------------------------------------------
// The Uses column
// ---------------------------------------------------------------------------

describe('the Uses column', () => {
  it('counts casts, so an ability dealing no damage still has a row', () => {
    /*
     * Battle Shout, Sunder Armor, Bloodrage and every stance were invisible
     * in this table. A rotation could be casting one forty times a fight and
     * the only evidence was the rage it spent.
     */
    const rows = berserker().abilities;
    const byName = new Map(rows.map((row) => [row.abilityName, row]));

    for (const name of ['Battle Shout', 'Sunder Armor', 'Bloodrage']) {
      const row = byName.get(name);
      expect(row, name).toBeDefined();
      expect(row!.damage, name).toBe(0);
      expect(row!.uses, name).toBeGreaterThan(0);
    }
  });

  it('counts them for damaging abilities too', () => {
    const whirlwind = berserker().abilities.find((r) => r.abilityName === 'Whirlwind')!;
    expect(whirlwind.uses).toBeGreaterThan(0);
    expect(whirlwind.damage).toBeGreaterThan(0);
  });

  it('reports ZERO uses for damage nobody cast', () => {
    /*
     * An auto attack, a weapon proc and a bleed tick are damage without a
     * use. Counting them as uses would make "casts per fight" meaningless.
     */
    const rows = berserker().abilities;
    const byName = new Map(rows.map((row) => [row.abilityName, row]));
    expect(byName.get('Main Hand Auto-Attack')!.uses).toBe(0);
    expect(byName.get('Off Hand Auto-Attack')!.uses).toBe(0);
    expect(byName.get('Fatal Wound')!.uses).toBe(0);
  });

  it('counts an on-next-swing ability once per arming', () => {
    /*
     * Heroic Strike is armed and then replaces a swing. The arming is the
     * cast; the swing that consumes it does not emit a second one, so uses
     * and rage-spend count agree.
     */
    const result = berserker();
    const row = result.abilities.find((r) => r.abilityName === 'Heroic Strike')!;
    const spent = result.rage.spent.find((r) => r.sourceId === 'heroic_strike')!;
    expect(row.uses).toBeCloseTo(spent.count, 1);
  });
});
