import type { PartialStats, WeaponProfile } from '../../engine';
import { Combatant, addStats, makeStats } from '../../engine';
import { abilitiesForClass } from '../abilities/exampleAbilities';
import type { ClassId, FormId, RaceId } from '../character';
import {
  baseHitPointsFor,
  baseManaFor,
  baseStatsFor,
  baseStatsToEngineStats,
  resourceSpecsFor,
} from '../character';
import { BASIC_MELEE_ROTATION } from '../rotations/basicMeleeRotation';

/** Default weapon for the example player. */
export const EXAMPLE_WEAPON: WeaponProfile = {
  name: 'Melee',
  swingTimerMs: 2600,
  baseDamage: 80,
  damageVariance: 0.15,
  powerCoefficient: 0.35,
  school: 'physical',
  // Rage is generated by attacking. Classes that do not use rage simply have no
  // pool for this to land in, and `grantResource` ignores it.
  generates: { resource: 'rage', amount: 15 },
};

export interface PlayerOptions {
  readonly id?: string;
  readonly name?: string;
  readonly race: RaceId;
  readonly characterClass: ClassId;
  /** Only meaningful for the Druid. Defaults to the class's default form. */
  readonly form?: FormId;
  /**
   * Stats from gear, buffs and anything else on top of the race/class base.
   * Added to the base rather than replacing it.
   */
  readonly bonusStats?: PartialStats;
  readonly weapon?: WeaponProfile;
}

/**
 * Build a player combatant for a race, class and form.
 *
 * Health, mana and every primary stat come from the base stats table. Anything
 * passed in as `bonusStats` is ADDED to that base, matching how gear works: a
 * profile describes what a character has beyond being a level 60 Tauren Druid,
 * not their stats from scratch.
 *
 * Crit chance is not applied. The base table's crit values are class constants
 * that other contributions add to, some of them negative, and the
 * agility-to-crit conversion that completes the formula does not exist yet.
 */
export function createPlayer(options: PlayerOptions): Combatant {
  const { race, characterClass, form } = options;

  const base = baseStatsFor(race, characterClass, form);
  if (!base) {
    throw new Error(
      `No base stats for ${race} ${characterClass}` +
        (form ? ` in ${form} form` : '') +
        '. Is that a legal combination?',
    );
  }

  const stats = addStats(
    makeStats(baseStatsToEngineStats(base)),
    options.bonusStats ?? {},
  );

  const abilities = abilitiesForClass(characterClass);

  return new Combatant({
    id: options.id ?? 'player_1',
    name: options.name ?? 'Player',
    kind: 'player',
    faction: 'friendly',
    maxHealth: baseHitPointsFor(race, characterClass, form),
    stats,
    resources: resourceSpecsFor(characterClass, baseManaFor(race, characterClass)),
    abilities,
    // No abilities means nothing for a rotation to choose, so it is left off
    // rather than scheduling decision events that can never do anything.
    rotation: abilities.length > 0 ? BASIC_MELEE_ROTATION : undefined,
    weapon: options.weapon ?? EXAMPLE_WEAPON,
  });
}
