import type { PartialStats, WeaponProfile } from '../../engine';
import { Combatant, addStats, makeStats } from '../../engine';
import { abilitiesForClass } from '../abilities/exampleAbilities';
import type { ClassId, FormId, RaceId } from '../character';
import {
  baseHitPointsFor,
  baseManaFor,
  baseStatsFor,
  baseStatsToEngineStats,
  conversionsFor,
  deriveFromPrimaries,
  resourceSpecsFor,
  statDerivationFor,
} from '../character';
import { BASIC_MELEE_ROTATION } from '../rotations/basicMeleeRotation';

/** Default weapon for the example player. */
export const EXAMPLE_WEAPON: WeaponProfile = {
  name: 'Melee',
  swingTimerMs: 2600,
  baseDamage: 80,
  damageVariance: 0.15,
  powerCoefficient: 0.35,
  school: 'physical',
  // Rage is generated by attacking. Classes that do not use rage simply have no
  // pool for this to land in, and `grantResource` ignores it.
  generates: { resource: 'rage', amount: 15 },
};

export interface PlayerOptions {
  readonly id?: string;
  readonly name?: string;
  readonly race: RaceId;
  readonly characterClass: ClassId;
  /** Only meaningful for the Druid. Defaults to the class's default form. */
  readonly form?: FormId;
  /**
   * Stats from gear, buffs and anything else on top of the race/class base.
   * Added to the base rather than replacing it.
   */
  readonly bonusStats?: PartialStats;
  readonly weapon?: WeaponProfile;
}

/**
 * Build a player combatant for a race, class and form.
 *
 * Three layers, in order:
 *
 *   1. **Base stats** for the race, class and form, from the spreadsheet.
 *   2. **Gear and other bonuses** from the profile, added on top.
 *   3. **Conversions**, which turn the resulting primary stats into attack
 *      power, armor, crit, dodge, mana regen, hit points and mana.
 *
 * Steps 1 and 2 happen here. Step 3 is handed to the stat block as a function,
 * so it re-runs whenever a buff changes a primary stat: a +10% strength
 * blessing raises attack power, which it would not if attack power had been
 * computed once and frozen.
 *
 * Hit points and mana are the exception. They are resource maximums rather than
 * stats, so they are computed once here from the starting stats. A buff that
 * changes stamina mid-fight will not currently resize the health pool.
 */
export function createPlayer(options: PlayerOptions): Combatant {
  const { race, characterClass, form } = options;

  const base = baseStatsFor(race, characterClass, form);
  if (!base) {
    throw new Error(
      `No base stats for ${race} ${characterClass}` +
        (form ? ` in ${form} form` : '') +
        '. Is that a legal combination?',
    );
  }

  // Layers 1 and 2: the stats a character has before any conversion.
  const startingStats = addStats(
    makeStats(baseStatsToEngineStats(base)),
    options.bonusStats ?? {},
  );

  // Layer 3, for the resource maximums only. The stat block handles the rest.
  const conversions = conversionsFor(characterClass, form);
  const derived = deriveFromPrimaries(startingStats, conversions);

  const abilities = abilitiesForClass(characterClass);

  return new Combatant({
    id: options.id ?? 'player_1',
    name: options.name ?? 'Player',
    kind: 'player',
    faction: 'friendly',
    maxHealth: baseHitPointsFor(race, characterClass, form) + derived.hitPoints,
    stats: startingStats,
    statDerivation: statDerivationFor(characterClass, form),
    resources: resourceSpecsFor(
      characterClass,
      baseManaFor(race, characterClass) + derived.mana,
    ),
    abilities,
    // No abilities means nothing for a rotation to choose, so it is left off
    // rather than scheduling decision events that can never do anything.
    rotation: abilities.length > 0 ? BASIC_MELEE_ROTATION : undefined,
    weapon: options.weapon ?? EXAMPLE_WEAPON,
  });
}
