import type { PartialStats, WeaponProfile } from '../../engine';
import { Combatant } from '../../engine';
import { abilitiesForClass } from '../abilities/exampleAbilities';
import type { ClassId } from '../character';
import { resourceSpecsFor } from '../character';
import { BASIC_MELEE_ROTATION } from '../rotations/basicMeleeRotation';

/** Default weapon for the example player. */
export const EXAMPLE_WEAPON: WeaponProfile = {
  name: 'Melee',
  swingTimerMs: 2600,
  baseDamage: 80,
  damageVariance: 0.15,
  powerCoefficient: 0.35,
  school: 'physical',
  // Rage is generated by attacking. Classes that do not use rage simply have no
  // pool for this to land in, and `grantResource` ignores it.
  generates: { resource: 'rage', amount: 15 },
};

export interface PlayerOptions {
  readonly id?: string;
  readonly name?: string;
  /** Determines which resource pools and abilities the character gets. */
  readonly characterClass: ClassId;
  readonly maxHealth?: number;
  readonly stats?: PartialStats;
  readonly weapon?: WeaponProfile;
  /** Overrides the placeholder mana pool once real mana data exists. */
  readonly maxMana?: number;
}

/**
 * Build a player combatant for a class.
 *
 * Resource pools come from the class definition rather than being hard-coded,
 * so a Mage gets mana and a Rogue gets energy. A Druid gets all three at once,
 * because changing form mid-fight must not have to conjure a pool that did not
 * exist a moment earlier.
 *
 * Abilities are still Warrior-only example content; every other class fights
 * with auto attacks alone until real class content is written.
 */
export function createPlayer(options: PlayerOptions): Combatant {
  const abilities = abilitiesForClass(options.characterClass);

  return new Combatant({
    id: options.id ?? 'player_1',
    name: options.name ?? 'Player',
    kind: 'player',
    faction: 'friendly',
    maxHealth: options.maxHealth ?? 1000,
    stats: {
      strength: 100,
      attackPower: 100,
      critRating: 0,
      hasteRating: 0,
      ...options.stats,
    },
    resources: resourceSpecsFor(options.characterClass, options.maxMana),
    abilities,
    // No abilities means nothing for a rotation to choose, so it is left off
    // rather than scheduling decision events that can never do anything.
    rotation: abilities.length > 0 ? BASIC_MELEE_ROTATION : undefined,
    weapon: options.weapon ?? EXAMPLE_WEAPON,
  });
}
