import type { AbilityModifier } from '../combat/abilityModifiers';
import {
  AbilityModifiers,
  AttackTableModifiers,
  SchoolModifiers,
  combineAbilityModifiers,
} from '../combat/abilityModifiers';
import type { AuraDefinition } from '../effects/Aura';
import type { Ability } from '../abilities/Ability';
import { DEFAULT_GCD_MS } from '../abilities/Ability';
import { AbilityBook } from '../abilities/AbilityBook';
import type { DamageSchool } from '../combat/DamageSchool';
import type { AttackTableKind } from '../combat/attackTable';
import type { CastReaction, Reaction } from '../combat/reactions';
import type { ScheduledEvent } from '../events';
import { AuraCollection } from '../effects';
import type { ResourceRegen, ResourceSpec, ResourceType } from '../resources';
import { Resource, ResourceCollection } from '../resources';
import type { Rotation } from '../rotation/Rotation';
import type { PartialStats, StatDerivation } from '../stats';
import { StatBlock } from '../stats';
import type { StatSampleValues } from '../logging/statSample';
import type { Milliseconds } from '../time';

/**
 * What kind of thing this combatant is.
 *
 * The simulation loop treats all of them identically; the kind exists so that
 * analysis can separate player output from pet output, and so that targeting
 * rules can eventually distinguish "an enemy" from "an add".
 */
export type CombatantKind = 'player' | 'enemy' | 'pet' | 'summon';

/** Who this combatant fights. Targeting uses this, not the kind. */
export type Faction = 'friendly' | 'hostile';

/** Where a weapon sits. Which of these swing is decided by the auto-attack mode. */
export type WeaponSlot = 'mainHand' | 'offHand' | 'ranged';

/**
 * Which weapons auto-attack.
 *
 * - `none`       nothing swings (casters)
 * - `main-hand`  the main hand only (two-handers, sword and board, bear, cat)
 * - `dual-wield` both hands, on independent timers
 * - `ranged`     the ranged weapon only
 */
export type AutoAttackMode = 'none' | 'main-hand' | 'dual-wield' | 'ranged';

/**
 * A weapon's auto-attack behaviour.
 *
 * Auto attacks are off the global cooldown and repeat on their own timer, so
 * they are not modelled as abilities. The numbers are content; the swing timer
 * scheduling is in `engine/combat/autoAttack.ts`.
 */
/**
 * What kind of weapon this is.
 *
 * The engine does not care -- damage is damage -- but content does: WoW is full
 * of "increases damage with axes" and "your maces ignore armor". Kept as a
 * closed union so a typo is a compile error, and `unknown` for a placeholder
 * weapon that never came from an item.
 */
export type WeaponType =
  | 'sword'
  | 'axe'
  | 'mace'
  | 'polearm'
  | 'staff'
  | 'dagger'
  | 'fist'
  | 'bow'
  | 'gun'
  | 'crossbow'
  | 'thrown'
  | 'wand'
  | 'unknown';

export interface WeaponProfile {
  readonly name: string;
  /** What kind of weapon it is, for content that cares. */
  readonly weaponType?: WeaponType;
  /** Whether it occupies both hands. */
  readonly twoHanded?: boolean;
  /** Unhasted time between swings. */
  readonly swingTimerMs: Milliseconds;
  /** Average damage per swing before attack power. */
  readonly baseDamage: number;
  /** Damage rolls uniformly within this fraction of base. 0.15 is +/-15%. */
  readonly damageVariance?: number;
  /** Attack power contribution per swing. */
  readonly powerCoefficient?: number;
  /**
   * The same, at the ruleset's NORMALISED speed for this kind of weapon.
   *
   * Used only by abilities that declare `weaponScaling.normalized`, and
   * computed by `game` because the speeds are ruleset content. A weapon
   * without one falls back to `powerCoefficient`, so a paw or a placeholder
   * is un-normalised rather than powerless.
   */
  readonly normalizedPowerCoefficient?: number;
  /**
   * The wielder's skill with this weapon.
   *
   * Compared against the target's defense skill to derive miss, dodge and
   * glancing chances. Defaults to five times the wielder's level, which is the
   * maximum an untalented character can have.
   */
  readonly skill?: number;
  /**
   * Multiplies this weapon's entire auto-attack, base damage and attack power
   * contribution alike. Defaults to 1.
   *
   * Exists for the dual-wield off-hand penalty, which is a property of the hand
   * rather than of the weapon in it. Talents that change that penalty adjust
   * this value when the character is built.
   */
  readonly damageMultiplier?: number;
  readonly school?: DamageSchool;
  /** Resource generated by landing a swing, if any. */
  readonly generates?: ResourceGeneration;
}

/**
 * Resource granted by an event, either as a flat amount or in proportion to the
 * damage involved.
 *
 * Both exist because rulesets use both: a flat award per swing is simple, while
 * rage is proportional to damage actually dealt, so a miss generates nothing and
 * a big hit generates more.
 */
export interface ResourceGeneration {
  readonly resource: ResourceType;
  /** Granted once per event, regardless of how much damage there was. */
  readonly flat?: number;
  /** Multiplied by the damage involved. */
  readonly perDamage?: number;
  /**
   * Whether a `flat` award needs the event to have dealt damage at all.
   *
   * A `perDamage` award is self-limiting -- no damage, nothing granted -- but a
   * flat one is not, and a swing that MISSED is still an event. Forever's rage
   * is a flat amount per swing and is still rage from damage DEALT, so it needs
   * both halves: the size of the award does not depend on the damage, and its
   * existence does.
   *
   * Left off by default, because a ruleset that genuinely pays per swing
   * regardless of outcome is a reasonable thing to want.
   */
  readonly requiresDamage?: boolean;
}

/** The refund an avoided ability gets, and which resources it applies to. */
export interface CostRefundRule {
  /** 0.8 is "80% of the cost back". */
  readonly fraction: number;
  readonly resources: readonly ResourceType[];
}

export interface CombatantOptions {
  readonly id: string;
  readonly name: string;
  readonly kind: CombatantKind;
  readonly faction: Faction;
  readonly maxHealth: number;
  /**
   * Character or creature level. Drives the skill difference that shapes the
   * combat tables, and the armor constant. Defaults to 60.
   */
  readonly level?: number;
  readonly stats?: PartialStats;
  readonly resources?: readonly ResourceSpec[];
  readonly abilities?: readonly Ability[];
  readonly rotation?: Rotation;
  /**
   * Auras applied to this combatant the moment combat begins.
   *
   * For a state a character is simply always in, rather than a buff someone
   * cast. A Warrior is always in a stance, and starting in none made every
   * stance-gated ability uncastable -- which is technically what the rules say
   * and is not what the rules mean.
   *
   * NOT a place for raid buffs. Those are an encounter's business and belong in
   * `trainingDummyEncounter`, where a reader can see what was assumed.
   */
  readonly openingAuras?: readonly AuraDefinition[];
  /** Weapons by slot. Which ones swing is decided by `autoAttack`. */
  readonly weapons?: Partial<Record<WeaponSlot, WeaponProfile>>;
  /**
   * Extra hit chance that applies only when a particular hand swings.
   *
   * Percentage POINTS, added to the character-wide hit stat by the combat
   * table. A whole-character stat cannot express it: Dual Wield
   * Specialization gives ten points of hit to the OFF HAND only, and folding
   * that into `hitChance` would hand the main hand ten free points too.
   */
  readonly hitBonusBySlot?: Partial<Record<WeaponSlot, number>>;
  /**
   * How long this combatant's global cooldown is, before haste.
   *
   * On the COMBATANT rather than on each ability, because it is a property of
   * the class: Forever gives most classes 1.5 seconds and gives a Rogue, or a
   * Druid in Cat Form, 1.0 -- for the same abilities. An ability that needs a
   * different one still overrides it with `gcdMs`.
   */
  readonly baseGcdMs?: Milliseconds;
  /**
   * What an ability gets back when its attack does not connect.
   *
   * ----------------------------------------------------------------------------
   * ON THE COMBATANT, NOT THE ABILITY, for the same reason `baseGcdMs` is: the
   * fraction and the resources it applies to are RULESET content, and the same
   * Sinister Strike refunds or does not depending on the ruleset rather than on
   * anything about the ability.
   *
   * An ability opts OUT with `refundsCostOnMiss: false`; it never opts in. A
   * new rage or energy ability therefore gets the rule for free, which is the
   * same derivation argument the global cooldown uses -- the failure mode of
   * declaring it per ability is silent, because an ability that wrongly keeps
   * its cost still deals the right damage.
   * ----------------------------------------------------------------------------
   */
  readonly costRefundOnMiss?: CostRefundRule;
  /** Defaults to `none`: a combatant with no declared mode does not swing. */
  readonly autoAttack?: AutoAttackMode;
  /** Resources that refill on a timer. */
  readonly regeneration?: readonly ResourceRegen[];
  /**
   * Resource granted when this combatant TAKES damage. How a warrior builds
   * rage from being hit.
   */
  readonly resourceOnDamageTaken?: ResourceGeneration;
  /**
   * Turns primary stats into the secondary stats they produce, re-run whenever
   * a buff changes a primary stat. The conversion numbers are class content, so
   * the engine takes a function rather than knowing them.
   */
  readonly statDerivation?: StatDerivation;
  /**
   * Things that happen in response to an attack result: a Warrior's Overpower
   * becoming available because the target dodged. Content, like the derivation
   * above.
   */
  readonly reactions?: readonly Reaction[];
  /**
   * Reactions to a cast rather than to an attack.
   *
   * A separate list because a cast event is not an attack event -- see
   * `CastEvent`. Everything that reacts to being hit stays where it was.
   */
  readonly castReactions?: readonly CastReaction[];
  /**
   * Per-ability crit and damage modifiers, from talents, gear or anything else
   * that changes one ability rather than the whole character.
   */
  readonly abilityModifiers?: AbilityModifiers;
  readonly schoolModifiers?: SchoolModifiers;
  readonly attackTableModifiers?: AttackTableModifiers;
  /**
   * The same table-scoped modifiers, counted ONLY while the target bleeds.
   *
   * ----------------------------------------------------------------------------
   * THE SAME CLASS, A SECOND INSTANCE, rather than a new shape. "Increases
   * damage done by your melee abilities on Bleeding targets" is
   * `AttackTableModifiers` in every respect but one: whether it counts is a
   * question about somebody ELSE, answered on each hit.
   *
   * Kept apart from `attackTableModifiers` for the reason
   * `AbilityModifiers.addWhileAura` is kept apart from `add` -- combining a
   * conditional modifier into the unconditional bucket loses the condition, and
   * a talent that pays all fight instead of during its window is a bigger
   * number and no error.
   * ----------------------------------------------------------------------------
   */
  readonly bleedingTargetModifiers?: AttackTableModifiers;
  /**
   * A permanent multiplier on every PERIODIC point of damage, on top of
   * `damageMultiplier`.
   *
   * Genesis is "increases the periodic damage and healing done by your spells
   * and abilities", which selects on the one thing no other scope can see:
   * whether the damage is a tick. `DamageRequest.periodic` has carried that
   * since the first DoT, so this is a new reader of an old fact.
   */
  readonly periodicDamageMultiplier?: number;
  /**
   * A permanent multiplier on every point of damage this combatant deals,
   * multiplied together with whatever auras contribute.
   *
   * For an effect decided when the character is built rather than during the
   * fight -- a talent conditional on the weapon held, a set bonus. An effect
   * that comes and goes belongs in an aura, which has the lifecycle for it.
   */
  readonly damageMultiplier?: number;
  /**
   * Damage cannot take this combatant below one health.
   *
   * For a raid encounter where a HEALER IS ASSUMED BUT NOT MODELLED. The damage
   * still lands in full -- it is still reported, and still generates rage --
   * the character simply does not fall over partway through and end the fight.
   *
   * SURVIVAL IS THEREFORE NOT MODELLED. A run with this set says nothing about
   * whether the character would live; it exists so that the things incoming
   * damage TRIGGERS can be measured at all.
   */
  readonly survivesLethalDamage?: boolean;
  /**
   * Death is recorded and then undone: health returns to full and the fight
   * carries on.
   *
   * The OTHER answer to the same question `survivesLethalDamage` answers, and
   * the two are mutually exclusive. Both exist so that a fight can run its
   * full length against a target that hits back, and they differ in what they
   * are willing to hide:
   *
   *   - `survivesLethalDamage` never lets health reach zero, so nothing ever
   *     dies and a death cannot be counted. It measures what incoming damage
   *     TRIGGERS while saying nothing about survival.
   *   - `revivesOnDeath` lets the character die, RECORDS it, and stands them
   *     back up. Deaths become a number, and everything a death implies --
   *     lost health, overkill -- is real.
   *
   * It is still not a survival model: something is putting the character back
   * on their feet, and nothing in the ruleset says what. What it gives is a
   * count of how often the encounter as configured would have killed them.
   *
   * Auras are NOT dropped, unlike a real death. Survival is what is being
   * measured, not a death-and-rebuff cycle, and dropping them would silently
   * cancel the very effects the run exists to exercise -- including whatever
   * is doing the healing.
   */
  readonly revivesOnDeath?: boolean;
  /** For pets and summons: the id of the combatant that owns them. */
  readonly ownerId?: string;
}

/**
 * Anything that participates in combat: a player, a boss, a pet, an add.
 *
 * There is one class rather than a Player/Enemy hierarchy, because every
 * difference between them turned out to be data (a rotation, a weapon, a
 * faction) rather than behaviour. The simulation holds a flat collection of
 * these, which is what lets the same engine run 1v1 and a 20-player raid
 * without a second code path.
 */
export class Combatant {
  readonly id: string;
  readonly name: string;
  readonly kind: CombatantKind;
  readonly faction: Faction;
  readonly level: number;
  readonly ownerId: string | undefined;

  readonly stats: StatBlock;
  readonly health: Resource;
  readonly resources: ResourceCollection;
  readonly auras: AuraCollection;
  /** Applied by the simulation when combat begins. See the option. */
  readonly openingAuras: readonly AuraDefinition[];
  readonly abilities: AbilityBook;
  readonly rotation: Rotation | undefined;
  readonly weapons: Partial<Record<WeaponSlot, WeaponProfile>>;
  readonly hitBonusBySlot: Partial<Record<WeaponSlot, number>>;
  readonly baseGcdMs: Milliseconds;
  readonly autoAttack: AutoAttackMode;
  readonly costRefundOnMiss?: CostRefundRule;
  /*
   * WHAT THE CAST IN FLIGHT PAID, so an avoided attack can hand most of it
   * back. Cleared by the first damage this ability resolves, whether that
   * damage landed or not -- so Whirlwind's off hand missing after its main
   * hand connected refunds nothing, which is right: the ability connected.
   */
  pendingCostRefund?: { abilityId: string; resource: ResourceType; amount: number };
  /**
   * WHICH TARGET this combatant's combo points are on.
   *
   * Combo points live on the victim rather than on the Rogue, so they are lost
   * when a builder lands on someone else. One enemy today makes that
   * unobservable; the field exists so the rule is right rather than remembered
   * the day an encounter has adds.
   */
  comboPointTargetId?: string;
  readonly regeneration: readonly ResourceRegen[];
  readonly resourceOnDamageTaken: ResourceGeneration | undefined;
  readonly reactions: readonly Reaction[];
  readonly castReactions: readonly CastReaction[];
  readonly abilityModifiers: AbilityModifiers;
  /** Per-school crit, crit damage and damage. See `SchoolModifiers`. */
  readonly schoolModifiers: SchoolModifiers;
  /** Crit, crit damage and damage scoped to MELEE or RANGED. See the class. */
  readonly attackTableModifiers: AttackTableModifiers;
  /** The same, counted only while the target bleeds. See the option. */
  readonly bleedingTargetModifiers: AttackTableModifiers;
  readonly baseDamageMultiplier: number;
  /** Multiplies periodic damage only. See the option. */
  readonly periodicDamageMultiplier: number;
  readonly survivesLethalDamage: boolean;
  readonly revivesOnDeath: boolean;

  /**
   * When each resource was last spent.
   *
   * Recorded so that rules keyed on recent spending can be expressed: mana
   * regeneration stops for five seconds after a cast. Kept per resource rather
   * than as a single timestamp, because spending rage says nothing about
   * whether mana should be regenerating.
   */
  private readonly lastSpend = new Map<ResourceType, Milliseconds>();

  /**
   * When this combatant's global cooldown ends. Shared across abilities, which
   * is why it lives here rather than on any one of them.
   */
  gcdReadyAt: Milliseconds = 0;

  /** When the current cast finishes, or 0 when not casting. */
  castEndsAt: Milliseconds = 0;

  /**
   * An ability armed to replace the next swing of a weapon, by slot.
   *
   * Heroic Strike and Cleave are "on next swing": they are paid for and armed,
   * then land as part of the following auto-attack rather than on their own.
   * Held here rather than in the ability book because it is per-combatant
   * state about a weapon, not about a cooldown.
   */
  private readonly queuedSwings = new Map<WeaponSlot, string>();

  /**
   * The scheduled swing each weapon is waiting on.
   *
   * Kept so an extra attack can cancel and replace it. Swings reschedule
   * themselves, so nothing else needs the handle; without it, "resets the swing
   * timer" cannot be expressed at all.
   */
  private readonly pendingSwings = new Map<WeaponSlot, ScheduledEvent>();

  /** Record, or clear, the swing a slot is waiting on. */
  setPendingSwing(slot: WeaponSlot, handle: ScheduledEvent | null): void {
    if (handle) this.pendingSwings.set(slot, handle);
    else this.pendingSwings.delete(slot);
  }

  /** The swing a slot is waiting on, if any. */
  pendingSwing(slot: WeaponSlot): ScheduledEvent | undefined {
    return this.pendingSwings.get(slot);
  }

  /** Arm an ability to replace the next swing of a slot. */
  queueNextSwing(slot: WeaponSlot, abilityId: string): void {
    this.queuedSwings.set(slot, abilityId);
  }

  /** The ability armed for a slot, if any. */
  queuedSwing(slot: WeaponSlot): string | undefined {
    return this.queuedSwings.get(slot);
  }

  /** Take the armed ability for a slot, clearing it. */
  takeQueuedSwing(slot: WeaponSlot): string | undefined {
    const abilityId = this.queuedSwings.get(slot);
    this.queuedSwings.delete(slot);
    return abilityId;
  }

  private alive = true;

  /**
   * True while this combatant's reactions are running.
   *
   * A reaction that deals damage re-enters the damage pipeline, which would
   * offer the same actor its reactions again. This stops that recursion without
   * preventing a different combatant from reacting to what the reaction did.
   */
  private reacting = false;

  constructor(options: CombatantOptions) {
    this.id = options.id;
    this.name = options.name;
    this.kind = options.kind;
    this.faction = options.faction;
    this.level = options.level ?? 60;
    this.ownerId = options.ownerId;

    this.stats = new StatBlock(options.stats, options.statDerivation);
    this.health = new Resource('health', options.maxHealth);
    this.openingAuras = options.openingAuras ?? [];
    this.resources = new ResourceCollection(options.resources ?? []);
    this.auras = new AuraCollection(this);
    this.abilities = new AbilityBook(options.abilities ?? []);
    this.rotation = options.rotation;
    this.weapons = options.weapons ?? {};
    this.hitBonusBySlot = options.hitBonusBySlot ?? {};
    this.baseGcdMs = options.baseGcdMs ?? DEFAULT_GCD_MS;
    this.autoAttack = options.autoAttack ?? 'none';
    this.costRefundOnMiss = options.costRefundOnMiss;
    this.regeneration = options.regeneration ?? [];
    this.resourceOnDamageTaken = options.resourceOnDamageTaken;
    this.reactions = options.reactions ?? [];
    this.castReactions = options.castReactions ?? [];
    this.abilityModifiers = options.abilityModifiers ?? new AbilityModifiers();
    this.schoolModifiers = options.schoolModifiers ?? new SchoolModifiers();
    this.attackTableModifiers = options.attackTableModifiers ?? new AttackTableModifiers();
    this.bleedingTargetModifiers =
      options.bleedingTargetModifiers ?? new AttackTableModifiers();
    this.baseDamageMultiplier = options.damageMultiplier ?? 1;
    this.periodicDamageMultiplier = options.periodicDamageMultiplier ?? 1;
    this.survivesLethalDamage = options.survivesLethalDamage ?? false;
    this.revivesOnDeath = options.revivesOnDeath ?? false;
  }

  get isAlive(): boolean {
    return this.alive && !this.health.isEmpty;
  }

  /**
   * True once the simulation has run this combatant's death handling.
   *
   * Distinct from `!isAlive`, which is also true in the instant between health
   * hitting zero and the death being processed. The simulation uses this to
   * make killing idempotent.
   */
  get isDeathProcessed(): boolean {
    return !this.alive;
  }

  get isPlayerControlled(): boolean {
    return this.kind === 'player' || this.kind === 'pet' || this.kind === 'summon';
  }

  isHostileTo(other: Combatant): boolean {
    return this.faction !== other.faction;
  }

  isCasting(now: Milliseconds): boolean {
    return this.castEndsAt > now;
  }

  isOnGcd(now: Milliseconds): boolean {
    return this.gcdReadyAt > now;
  }

  /**
   * Multiplies damage this combatant deals. The product of every active aura
   * that declares one.
   *
   * Recomputed on each hit rather than cached: aura sets are small, and a stale
   * cached multiplier is a far nastier bug than a few extra multiplications.
   */
  get damageDoneMultiplier(): number {
    return this.baseDamageMultiplier * this.auraMultiplier('damageDoneMultiplier');
  }

  /**
   * How much more (or less) damage of one school this combatant DEALS.
   *
   * Folds the blanket multiplier in, exactly as `damageTakenMultiplierFor` does
   * on the other side, so a caller reads one number rather than remembering to
   * multiply two. Schools no active aura names are untouched.
   */
  damageDoneMultiplierFor(school: DamageSchool): number {
    let product = this.damageDoneMultiplier;
    for (const aura of this.auras.active) {
      const bySchool = aura.definition.damageDoneBySchool;
      if (bySchool?.[school] === undefined) continue;
      // Compounds with stacks, matching `auraMultiplier` and the target side.
      product *=
        bySchool[school]! ** (aura.definition.modifiersScaleWithStacks ? aura.stacks : 1);
    }
    return product;
  }

  /** Multiplies damage this combatant takes. */
  get damageTakenMultiplier(): number {
    return this.auraMultiplier('damageTakenMultiplier');
  }

  /** Multiplies healing this combatant does. */
  get healingDoneMultiplier(): number {
    return this.auraMultiplier('healingDoneMultiplier');
  }

  /**
   * This combatant's skill with the weapon in a slot.
   *
   * Falls back to five times its level, the maximum an untalented character
   * reaches, so a weapon that does not state a skill is treated as fully
   * trained rather than unskilled.
   */
  /** Extra hit, in percentage points, that only this hand gets. */
  hitBonusFor(slot: WeaponSlot): number {
    return this.hitBonusBySlot[slot] ?? 0;
  }

  weaponSkill(slot: WeaponSlot): number {
    return this.weapons[slot]?.skill ?? this.level * 5;
  }

  /** Five times level, the baseline every character has for free. */
  get baseDefenseSkill(): number {
    return this.level * 5;
  }

  /**
   * Defense skill: the level baseline plus whatever raised it.
   *
   * The `defenseSkill` stat holds only the surplus, because five per level is
   * a property of being level 60 and not something a talent granted. Keeping
   * the two apart is what lets the received table charge for the SURPLUS --
   * the boss's flat miss, crit and crush figures are already calibrated for a
   * character at the baseline, so counting all 300 points would move them by
   * twelve percent before a single talent was spent.
   */
  get defenseSkill(): number {
    return this.baseDefenseSkill + this.stats.get('defenseSkill');
  }

  /**
   * The per-ability modifier in force right now: the STANDING one plus
   * whatever active auras contribute.
   *
   * ----------------------------------------------------------------------------
   * `abilityModifiers` is built once and is not mutated during a fight, which
   * is right -- a talent or a set bonus is decided before the pull. An effect
   * that comes and goes belongs in an aura, and this is where the two meet.
   *
   * EVERY READER MUST COME THROUGH HERE, or an aura-granted modifier applies in
   * one half of the damage pipeline and not the other: the crit chance is read
   * in `rollTable` and the damage multiplier in `resolveDamage`, and a Berserk
   * that raised the crit chance without the multiplier following would be
   * quietly half an effect.
   * ----------------------------------------------------------------------------
   */
  abilityModifierFor(
    abilityId: string | undefined,
    /**
     * What fraction of the fight's PLANNED duration is still to come, for the
     * modifiers conditional on the clock.
     *
     * Optional, and NOT optional in the way that quietly drops them: a
     * character carrying one of those and a caller with no clock is a throw,
     * not a zero. See `AbilityModifiers.forWhileFinalFraction`. Every caller
     * that resolves real damage has a `SimulationContext` and passes it; the
     * ones that omit it are tests handing an outcome in directly.
     */
    remainingFraction?: number,
  ): AbilityModifier {
    const standing = this.abilityModifiers.for(abilityId);
    const fromAuras = this.auras.abilityModifierFor(abilityId);
    /*
     * THE THIRD SOURCE IS A STANDING MODIFIER WITH A RUNTIME CONDITION: it was
     * registered before the pull like the first, and it counts only while the
     * aura it names is up, like the second. Shatter is the first caller -- its
     * crit belongs to the Mage and its window belongs to Fingers of Frost, and
     * the two are separate talents. See `AbilityModifiers.addWhileAura`.
     */
    const whileAura = this.abilityModifiers.forWhileAura(abilityId, (auraId) =>
      this.auras.has(auraId),
    );
    /*
     * AND THE FOURTH IS CONDITIONED ON THE FIGHT RATHER THAN ON THE CHARACTER.
     * Early Demise on the Priest and Quietus on the Rogue both read "against
     * targets at or below N% health", which this project rules is the CLOCK --
     * the last N of the planned duration. A combatant holds no clock, which is
     * why the answer arrives as an argument.
     */
    const whileFinal = this.abilityModifiers.forWhileFinalFraction(abilityId, remainingFraction);
    let combined = fromAuras ? combineAbilityModifiers(standing, fromAuras) : standing;
    if (whileAura) combined = combineAbilityModifiers(combined, whileAura);
    if (whileFinal) combined = combineAbilityModifiers(combined, whileFinal);
    return combined;
  }

  /**
   * The per-ability modifier an attack AGAINST this combatant picks up, from
   * the debuffs it is carrying.
   *
   * ----------------------------------------------------------------------------
   * THE OTHER SIDE OF `abilityModifierFor`, and the same rule about readers
   * applies: every one comes through here, or a debuff that raised the crit
   * chance without the damage multiplier following would be quietly half an
   * effect.
   *
   * ONLY AURAS, with no standing registry behind it. A debuff is by definition
   * something that comes and goes, so there is nothing for a build-time
   * collection to hold -- unlike the attacker's side, where a talent's
   * permanent bonus and an aura's temporary one meet.
   *
   * WINTER'S CHILL IS THE FIRST CALLER: "increases the chance your Ice Lance
   * and Frostbolt spells will critically hit the target", which is a crit
   * bonus for two named abilities held by the boss.
   * ----------------------------------------------------------------------------
   */
  abilityModifierAgainst(abilityId: string | undefined): AbilityModifier {
    return this.auras.attackerAbilityModifierFor(abilityId) ?? {};
  }

  /**
   * When each weapon slot last completed a swing.
   *
   * ----------------------------------------------------------------------------
   * `pendingSwing` IS THE NEXT ONE, NOT THE LAST, and three Hunter entries want
   * the last: "only if a ranged auto-attack has fired in the last 0.5 seconds"
   * is how the owner's lists weave a cast into a shot cycle without throwing
   * the shot away.
   *
   * A cast RESETS the swing timer of the slot it interrupts, so a two-second
   * Aimed Shot started at the wrong moment discards most of a 3.2-second bow
   * cycle. Started just after a shot lands, it costs almost nothing -- and
   * "just after" is a question only this can answer.
   * ----------------------------------------------------------------------------
   */
  private readonly lastSwing = new Map<WeaponSlot, Milliseconds>();

  /**
   * The last stat sample emitted for this combatant, so the sampler can skip
   * an aura edge that moved none of them.
   *
   * Per-fight state on a per-fight object, like the swing timers above. Combat
   * start always emits with `force`, which re-bases it -- a test that hands the
   * same `Combatant` to two simulations would otherwise carry the first fight's
   * last value into the second and swallow its opening sample.
   */
  lastStatSample: StatSampleValues | undefined;

  /** Called by the engine when a swing resolves. */
  recordSwing(slot: WeaponSlot, at: Milliseconds): void {
    this.lastSwing.set(slot, at);
  }

  /** When this slot last swung, or undefined if it never has. */
  lastSwingAt(slot: WeaponSlot): Milliseconds | undefined {
    return this.lastSwing.get(slot);
  }

  /** Whether this slot swung within the last `windowMs`. */
  swungWithin(slot: WeaponSlot, now: Milliseconds, windowMs: Milliseconds): boolean {
    const last = this.lastSwing.get(slot);
    return last !== undefined && now - last <= windowMs;
  }

  /** Record that a resource was just spent. Called by the engine on payment. */
  recordResourceSpend(resource: ResourceType, at: Milliseconds): void {
    this.lastSpend.set(resource, at);
  }

  /** When this resource was last spent, or undefined if it never has been. */
  lastSpentAt(resource: ResourceType): Milliseconds | undefined {
    return this.lastSpend.get(resource);
  }

  /** Whether this resource was spent within the last `windowMs`. */
  spentWithin(resource: ResourceType, now: Milliseconds, windowMs: Milliseconds): boolean {
    const last = this.lastSpend.get(resource);
    return last !== undefined && now - last < windowMs;
  }

  /**
   * Claim the reaction lock. False when reactions are already running for this
   * combatant, in which case the caller must not run them again.
   */
  beginReacting(): boolean {
    if (this.reacting) return false;
    this.reacting = true;
    return true;
  }

  /** Release the reaction lock. Always paired with `beginReacting`. */
  endReacting(): void {
    this.reacting = false;
  }

  /** Mark as dead. Called by the simulation, not directly by content. */
  markDead(): void {
    this.alive = false;
    this.health.set(0);
  }

  /**
   * How much faster this combatant regenerates one resource right now.
   *
   * MULTIPLIED across auras, like every other multiplier here, so two sources
   * of "+100%" would give four times rather than three. Nothing stacks them
   * today; the rule is stated so the second one does not have to decide.
   */
  regenMultiplierFor(resource: ResourceType): number {
    let product = 1;
    for (const aura of this.auras.activeIterable) {
      const multiplier = aura.definition.resourceRegenMultiplier?.[resource];
      if (multiplier === undefined) continue;
      product *= multiplier;
    }
    return product;
  }

  /**
   * How much more (or less) damage of one school this combatant takes.
   *
   * Multiplied on TOP of `damageTakenMultiplier`, not instead of it: a target
   * under Curse of the Elements and a blanket damage-taken debuff is under
   * both. Schools an aura does not name are untouched.
   */
  damageTakenMultiplierFor(school: DamageSchool, periodic = false): number {
    let product = this.damageTakenMultiplier;
    for (const aura of this.auras.active) {
      /*
       * STACKS COMPOUND, matching `auraMultiplier` exactly rather than adding.
       *
       * Improved Scorch is "+3% Fire damage, stacking up to 5 times", and the
       * source does not say which. This engine already answers that question
       * for every other damage multiplier -- `modifiersScaleWithStacks` raises
       * it to the POWER of the stack count -- so 1.03 at five stacks is 1.159
       * and not 1.150. A one-percent difference, and a second convention for
       * the same flag would be worth far more trouble than it.
       */
      const exponent = aura.definition.modifiersScaleWithStacks ? aura.stacks : 1;
      const everyHit = aura.definition.damageTakenBySchool?.[school];
      if (everyHit !== undefined) product *= everyHit ** exponent;
      /*
       * BOTH FIELDS REACH A TICK, and they are separate rather than one flag.
       * `damageTakenBySchool` is every hit of that school;
       * `periodicDamageTakenBySchool` is Wrack's "damage over time effects"
       * clause and reaches a tick and nothing else. An aura declaring both puts
       * the target under both, so this multiplies rather than choosing.
       */
      if (!periodic) continue;
      const overTime = aura.definition.periodicDamageTakenBySchool?.[school];
      if (overTime !== undefined) product *= overTime ** exponent;
    }
    return product;
  }

  /**
   * Spell power of one school that an attacker hitting this combatant reads.
   *
   * ADDED across auras rather than multiplied, unlike every other per-school
   * figure here -- see `AuraDefinition.spellPowerTakenBySchool`. Two debuffs each
   * granting Holy power are one pool of Holy power, exactly as two rings each
   * granting strength are one pool of strength.
   */
  spellPowerTakenFor(school: DamageSchool): number {
    let total = 0;
    for (const aura of this.auras.active) {
      const bySchool = aura.definition.spellPowerTakenBySchool;
      const value = bySchool?.[school];
      if (value === undefined) continue;
      total += value * (aura.definition.modifiersScaleWithStacks ? aura.stacks : 1);
    }
    return total;
  }

  /**
   * How much more (or less) damage this combatant deals through one table,
   * from auras alone.
   *
   * The aura-shaped half of `attackTableModifiers`, which is fixed at build
   * time. Both apply: a standing talent bonus and a seal's temporary penalty are
   * different effects on the same swing.
   */
  damageDoneMultiplierForTable(table: AttackTableKind | undefined): number {
    if (table === undefined) return 1;
    let product = 1;
    for (const aura of this.auras.active) {
      const byTable = aura.definition.damageDoneByTable;
      const value = byTable?.[table];
      if (value === undefined) continue;
      product *= value ** (aura.definition.modifiersScaleWithStacks ? aura.stacks : 1);
    }
    return product;
  }

  private auraMultiplier(
    key: 'damageDoneMultiplier' | 'damageTakenMultiplier' | 'healingDoneMultiplier',
  ): number {
    let product = 1;
    for (const aura of this.auras.active) {
      const value = aura.definition[key];
      if (value !== undefined) {
        product *= value ** (aura.definition.modifiersScaleWithStacks ? aura.stacks : 1);
      }
    }
    return product;
  }
}
